### ISSUE TITLE
Script parameters

### ISSUE THREAD

**Issue by bolix** [devopsshield/azure-devops-workload-identity-federation#1]
When running the script what values should be used for WorkspaceName and ResourceGroupName? I am guessing Resource Group Name could be the resource group the current Service Principal has access to, but what about the workspace name?

This is part of the example:
./Convert-ServicePrincipals.ps1 
-WorkspaceName 'log-devopsshield-ek010devfd63l2gacbtca' 
     -ResourceGroupName  'rg-devopsshieldek010dev' `

**Comment by emmanuel-knafo** [comment]
@bolix, the resource group name as well as workspace name is the managed resource group name and log analytics workspace name if you have installed [DevOps Shield from the Azure Marketplace](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/cad4devopsinc1662079207461.devops-shield?src=website&mktcmpid=header). In the example above, this corresponds to: 
![image](https://github.com/devopsshield/azure-devops-workload-identity-federation/assets/112144174/42b67f82-cd13-4cef-abfa-f643be389cf4)

Alternatively, you can leverage the Azure DevOps CLI to loop over all service connections as in this [Microsoft Premier Developer Blog Post](https://devblogs.microsoft.com/premier-developer/azure-devops-workload-identity-federation/). For full details, see this [blog post](https://blog.devopsabcs.com/index.php/2023/09/23/azure-devops-workload-identity-federation/).
